package com.warehouse.dataTransfereObjects;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;

import java.math.BigDecimal;
import java.time.LocalDate;

//for creating a product: The id is intentionally absent: it is generated by the server so that clients cant choose or collide on ids. Validation annotations reject bad input before it ever reaches the service layer.
//unitsSold optional starting popularity count treated as 0 when omitted.

public record CreateProductRequest(
        @NotBlank(message = "name must not be blank")
        String name,

        @NotBlank(message = "category must not be blank")
        String category,

        @NotNull(message = "price is required")
        @PositiveOrZero(message = "price must be zero or positive")
        BigDecimal price,

        @PositiveOrZero(message = "quantity must be zero or positive")
        int quantity,

        @NotNull(message = "expiryDate is required")
        LocalDate expiryDate,

        @PositiveOrZero(message = "unitsSold must be zero or positive")
        Long unitsSold
) {
}
